---
galaxy_info:
  author: Kriti
  description: Deploy the Flask + Redis app via Docker Compose
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions: [noble]
  galaxy_tags: [docker, flask, redis]
dependencies:
  - role: docker
